### ISSUE TITLE
DwC Mapping - MIXS:0000093 elev

### ISSUE THREAD

**Issue by tucotuco** [tdwg/gbwg#15]
| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/verbatimElevation |
| subject_definition | The original description of the elevation (altitude, usually above sea level) of the Location. |
| subject_usage_notes |  |
| subject_examples | `100-200 m` |
| predicate_id | skos:broadMatch |
| object_id | MIXS:0000093 |
| object_label | elev |
| object definition | Elevation of the sampling site is its height above a fixed reference point, most commonly the mean sea level. Elevation is mainly used when referring to points on the earth's surface, while altitude is used for points above the surface, such as an aircraft in flight or a spacecraft in orbit |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment |  Going from MIxS to Darwin Core, the predicate would be skos:exactMatch, as the pattern in MIxS will always be acceptable on the Darwin Core side.

**Comment by raissameyer** [comment]
Should this term also be mapped to [dwc:maximumElevationInMeters](http://rs.tdwg.org/dwc/terms/version/maximumElevationInMeters-2017-10-06) and [dwc:minimumElevationInMeters](http://rs.tdwg.org/dwc/terms/version/minimumElevationInMeters-2017-10-06), following the same structure as the depth mappings in #13 ?

We should think about what criteria decide whether we map terms with multiple possible matches to only one or all.

**Comment by tucotuco** [comment]
It could be, but it is an indirect mapping with a potential calculation, whereas the verbatimElevation is an exactMatch.

**Comment by raissameyer** [comment]
Additional mapping options

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/minimumElevationInMeters |
| subject_definition | The lower limit of the range of elevation (altitude, usually above sea level), in meters.|
| subject_usage_notes |  |
| subject_examples | `-100`, `802` |
| predicate_id | skos:narrowMatch |
| object_id | MIXS:0000093 |
| object_label | elev |
| object definition | Elevation of the sampling site is its height above a fixed reference point, most commonly the mean sea level. Elevation is mainly used when referring to points on the earth's surface, while altitude is used for points above the surface, such as an aircraft in flight or a spacecraft in orbit |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment |  

and

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/maximumElevationInMeters |
| subject_definition | The upper limit of the range of elevation (altitude, usually above sea level), in meters. |
| subject_usage_notes |  |
| subject_examples | `-205`, `1236` |
| predicate_id | skos:narrowMatch |
| object_id | MIXS:0000093 |
| object_label | elev |
| object definition | Elevation of the sampling site is its height above a fixed reference point, most commonly the mean sea level. Elevation is mainly used when referring to points on the earth's surface, while altitude is used for points above the surface, such as an aircraft in flight or a spacecraft in orbit |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment |

**Comment by raissameyer** [comment]
As we have now decided to capture the syntax separately from the semantics, we can go back to the original mapping predicate `skos:exactMatch` for dwc:verbatimElevation and MIxS:elev

**Comment by raissameyer** [comment]
Suggested syntax predicates for the mapping above https://github.com/tdwg/gbwg/issues/15#issue-805156813

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/verbatimElevation |
| subject_value_syntax - expected_value - unit | verbatim |
| syntax_predicate_id | skos:broadMatch |
| object_id | MIXS:0000093 |
| object_value_syntax - expected_value - unit | {float} {unit} - measurement value - meter |
| syntax_comment | The DwC term expects verbatim input (so anything really), whereas MIxS expects {float} {unit} in meter |
