### ISSUE TITLE
DwC Mapping - MIXS:0000010 geo_loc_name

### ISSUE THREAD

**Issue by tucotuco** [tdwg/gbwg#16]
| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/higherGeography |
| subject_definition | A list (concatenated and separated) of geographic names less specific than the information captured in the locality term. |
| subject_usage_notes | Recommended best practice is to separate the values in a list with space vertical bar space ( &#124; ), with terms in order from least specific to most specific. |
| subject_examples | `North Atlantic Ocean`, "South America &#124; Argentina &#124; Patagonia &#124; Parque Nacional Nahuel Huapi &#124; Neuquén &#124; Los Lagos" (with accompanying values `South America` in continent, `Argentina` in country, `Neuquén` in stateProvince, and `Los Lagos` in county. |
| predicate_id | skos:exactMatch |
| object_id | MIXS:0000010 |
| object_label | geo_loc_name |
| object definition | The geographical origin of the sample as defined by the country or sea name followed by specific region name. Country or sea names should be chosen from the INSDC country list (http://insdc.org/country.html), or the GAZ ontology (v 1.512) (http://purl.bioontology.org/ontology/GAZ) |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment | DwC term encompasses any combination of geographic region names, while the MIxS term may either be the name of a country or a sea, followed by additional region information. |

**Comment by 79-6d** [comment]
Related issues for MIxS v6: 
- https://github.com/GenomicsStandardsConsortium/mixs/issues/79
- https://github.com/GenomicsStandardsConsortium/mixs/issues/25 (?)

**Comment by raissameyer** [comment]
Additional Mapping option:

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/country |
| subject_definition | The name of the country or major administrative unit in which the Location occurs.|
| subject_usage_notes | Recommended best practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names. |
| subject_value_syntax - expected_value - unit | {term} |
| subject_examples | `Denmark`, `Colombia`, `España`|
| predicate_id | skos:exactMatch |
| syntax_predicate_id | skos:relatedMatch |
| object_id | MIXS:0000010 |
| object_label | geo_loc_name |
| object definition | The geographical origin of the sample as defined by the country or sea name followed by specific region name. Country or sea names should be chosen from the INSDC country list (http://insdc.org/country.html), or the GAZ ontology (v 1.512) (http://purl.bioontology.org/ontology/GAZ) |
| object_value_syntax - expected_value - unit | country or sea name (INSDC or GAZ);region(GAZ);specific location name - {term};{term};{text} |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment | DwC term encompasses any combination of geographic region names, while the MIxS term may either be the name of a country or a sea, followed by additional region information. |
| syntax_comment | The DwC example only expects one word, while MIxS expects two words (country or sea name + specific region name). Additionally MIxS expects terms from an ontology where appropriate, for which the input would not only be a word but a termLabel[termID] combination |

**Comment by raissameyer** [comment]
Suggested syntax predicate for the mapping above https://github.com/tdwg/gbwg/issues/16#issue-805160075

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/higherGeography |
| subject_value_syntax - expected_value - unit | {term} &#124; {term} &#124; ... - geographic names |
| syntax_predicate_id | skos:relatedMatch |
| object_id | MIXS:0000010 |
| object_value_syntax - expected_value - unit | {term};{term};{text} - country or sea name (INSDC or GAZ);region(GAZ);specific location name |
| syntax_comment | DwC expects a list (of undefined length) of values separated by a vertical bar space  "|", while MIxS expects two words (country or sea name + specific region name). Additionally MIxS expects terms from an ontology where appropriate, for which the input would not only be a word but a termLabel[termID] combination |

**Comment by tucotuco** [comment]
Yes, it should be. Country and waterbody are disjunct concepts in Darwin
Core.

**Comment by raissameyer** [comment]
Additional Mapping option raised above:

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/waterBody |
| subject_definition | The name of the water body in which the Location occurs. |
| subject_usage_notes | Recommended best practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names. |
| subject_value_syntax - expected_value - unit | {term} |
| subject_examples | `Indian Ocean`, `Baltic Sea`, `Hudson River`, `Lago Nahuel Huapi`|
| predicate_id | skos:broadMatch |
| syntax_predicate_id | skos:relatedMatch |
| object_id | MIXS:0000010 |
| object_label | geo_loc_name |
| object definition | The geographical origin of the sample as defined by the country or sea name followed by specific region name. Country or sea names should be chosen from the INSDC country list (http://insdc.org/country.html), or the GAZ ontology (v 1.512) (http://purl.bioontology.org/ontology/GAZ) |
| object_value_syntax - expected_value - unit | country or sea name (INSDC or GAZ);region(GAZ);specific location name - {term};{term};{text} |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment | the MIxS term includes both seas and countries, while DwC only refers to the sea.|
| syntax_comment | The DwC example only expects one sea identifier, while MIxS expects an additional word (country or sea name + specific region name). Additionally, MIxS expects terms from an ontology where appropriate, for which the input would not only be a word but a termLabel[termID] combination |
