### ISSUE TITLE
DwC Mapping - MIXS:0000011 collection_date

### ISSUE THREAD

**Issue by tucotuco** [tdwg/gbwg#17]
| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/eventDate |
| subject_definition | The date-time or interval during which an Event occurred. For occurrences, this is the date-time when the event was recorded. Not suitable for a time in a geological context. |
| subject_usage_notes | Recommended best practice is to use a date that conforms to ISO 8601-1:2019. |
| subject_examples | `1963-03-08T14:07-0600` (8 Mar 1963 at 2:07pm in the time zone six hours earlier than UTC). `2009-02-20T08:40Z` (20 February 2009 8:40am UTC). `2018-08-29T15:19` (3:19pm local time on 29 August 2018). `1809-02-12` (some time during 12 February 1809). `1906-06` (some time in June 1906). `1971` (some time in the year 1971). `2007-03-01T13:00:00Z/2008-05-11T15:30:00Z` (some time during the interval between 1 March 2007 1pm UTC and 11 May 2008 3:30pm UTC). `1900/1909` (some time during the interval between the beginning of the year 1900 and the end of the year 1909). `2007-11-13/15` (some time in the interval between 13 November 2007 and 15 November 2007). | 
| predicate_id | skos:narrowMatch |
| object_id | MIXS:0000011 |
| object_label | collection_date |
| object definition | The time of sampling, either as an instance (single point in time) or interval. In case no exact time is available, the date/time can be right truncated i.e. all of these are valid times: 2008-01-23T19:23:10+00:00; 2008-01-23T19:23:10; 2008-01-23; 2008-01; 2008; Except: 2008-01; 2008 all are ISO8601 compliant |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment |  |

**Comment by raissameyer** [comment]
Suggested syntax predicate for the mapping above https://github.com/tdwg/gbwg/issues/17#issue-805162895

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/eventDate |
| subject_value_syntax - expected_value - unit | {timestamp} - date and time |
| syntax_predicate_id | skos:exactMatch |
| object_id | MIXS:0000011 |
| object_value_syntax - expected_value - unit | {timestamp} - date and time |
| syntax_comment | DwC requests compliance with ISO 8601-1:2019, so does MIxS |

**Comment by raissameyer** [comment]
> I think event date would be a narrowMatch to collection date, as events are semantically broader than sampling events (e.g. they could include observations too)

Thanks @pbuttigieg - I've updated our SSSOM matrix accordingly. 

@tucotuco would you mind updating the [mapping comment above](https://github.com/tdwg/gbwg/issues/17#issue-805162895) to reflect that as well?

**Comment by tucotuco** [comment]
That change gives me pause. I understand what @pbuttigieg is saying, but
any Event from Darwin Core that was being published in MIxS would be a
sampling Event anyway, and anything from MIxS going to Darwin Core would
just be an Event in Darwin Core, where there is no such thing as an Event
type. Basically, to me it seems an unnecessary complication to say it is a
narrowMatch. But then again, if I am right and it won't matter, then it
also won't matter that it is called a narrowMatch. So, if you still want me
to, I will make the change.

**Comment by tucotuco** [comment]
In discussion in the MIxS meeting 2021-05-26, the other types of Events than might be tracked were brought up, in which case a collecting event (and its date) would not be the only kind, thus a narrowMatch is an appropriate semantic relation. Table in the first comment updated.
