### ISSUE TITLE
DwC Mapping - MIXS:0000028 biotic_relationship

### ISSUE THREAD

**Issue by tucotuco** [tdwg/gbwg#19]
| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/associatedOrganisms |
| subject_definition | A list (concatenated and separated) of identifiers of other Organisms and their associations to this Organism. |
| subject_usage_notes |  |
| subject_examples | `"sibling of":"DMNS:Mamm http://arctos.database.museum/guid/DMNS:Mamm:14171"`, "parent of":"MSB:Mamm http://arctos.database.museum/guid/MSB:Mamm:196208" &#124; "parent of":"MSB:Mamm http://arctos.database.museum/guid/MSB:Mamm:196523" &#124; "sibling of":"MSB:Mamm http://arctos.database.museum/guid/MSB:Mamm:142638" |
| predicate_id | skos:exactMatch |
| object_id | MIXS:0000028 |
| object_label | biotic_relationship |
| object definition | Description of relationship(s) between the subject organism and other organism(s) it is associated with. E.g., parasite on species X; mutualist with species Y. The target organism is the subject of the relationship, and the other organism(s) is the object |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment | One could also capture relationships with more metadata about the assertion using the ResourceRelationship extension to Darwin Core. |

**Comment by raissameyer** [comment]
Suggested syntax predicate for the mapping above https://github.com/tdwg/gbwg/issues/19#issue-805168561

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/associatedOrganisms |
| subject_value_syntax - expected_value - unit | {"term"}:{"ID"}  | {"term"}:{"ID"} | ...  |
| syntax_predicate_id | skos:relatedMatch |
| object_id | MIXS:0000028 |
| object_value_syntax - expected_value - unit | [free living\|parasitism\|commensalism\|symbiotic\|mutualism] - enumeration |
| syntax_comment | DwC expects a list of terms and corresponding identifiers, while MIxS only expects a list of terms | 

DwC example:
> "parent of":"MSB:Mamm http://arctos.database.museum/guid/MSB:Mamm:196208" | "parent of":"MSB:Mamm http://arctos.database.museum/guid/MSB:Mamm:196523"

**Comment by raissameyer** [comment]
The current mapping is based on the definition, however the definition and value syntax and example don't match:

As @cmungall noted, the range of the MIxS term is [free living|parasitism|commensalism|symbiotic|mutualism]. 

While the expectation created by the definition [parasite on species X; mutualist with species Y] would exactly match the DwC term, the examples given by MIxS do not. 

Thus, we should consider revising the term (potentially to a skos:relatedMatch?)

**Comment by pbuttigieg** [comment]
Focusing on the MIxS value syntax, it would seem to me that the MIxS term is broader than the DwC term, as the latter will be more precise in any arbitrary case. 

E.g.  Some worm is a parasite of a clam
DwC would capture parasite of clam 
MIxS would capture parasite of

**Comment by raissameyer** [comment]
As noted in the [SSSOM guidance](https://github.com/mapping-commons/SSSOM/blob/master/SSSOM.md#common-mapping-predicates), skos:broadMatch "asserts that , the object of the triple, is a broader concept than, the subject of the triple"

As PLB noted [above](https://github.com/tdwg/gbwg/issues/19#issuecomment-866069427), the MIxS term is broader that the DwC term

Thus, our DwC --> MIxS mapping would be a skos:broadMatch

I'll update our mapping files accordingly.
