### ISSUE TITLE
DwC Mapping - MIXS:0000016 samp_mat_process

### ISSUE THREAD

**Issue by tucotuco** [tdwg/gbwg#21]
| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/samplingProtocol |
| subject_definition | The name of, reference to, or description of the method or protocol used during an Event. |
| subject_usage_notes |  |
| subject_examples | `UV light trap`, `mist net`, `bottom trawl`, `ad hoc observation`, `point count`, `Penguins from space: faecal stains reveal the location of emperor penguin colonies, https://doi.org/10.1111/j.1466-8238.2009.00467.x, Takats et al. 2001. Guidelines for Nocturnal Owl Monitoring in North America. Beaverhill Bird Observatory and Bird Studies Canada, Edmonton, Alberta. 32 pp., http://www.bsc-eoc.org/download/Owl.pdf` |
| predicate_id | skos:broadMatch |
| object_id | MIXS:0000016 |
| object_label | samp_mat_process |
| object definition | Any processing applied to the sample during or after retrieving the sample from environment. This field accepts OBI, for a browser of OBI (v 2018-02-12) terms please see http://purl.bioontology.org/ontology/OBI |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment | dwc:samplingProtocol covers both of the concepts samp_collect_device and samp_collect_process. |

**Comment by 79-6d** [comment]
Related MIxS v6 issue: https://github.com/GenomicsStandardsConsortium/mixs/issues/21

**Comment by raissameyer** [comment]
Suggested syntax predicate for the mapping above https://github.com/tdwg/gbwg/issues/21#issue-805171660

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/samplingProtocol |
| subject_value_syntax - expected_value - unit |  |
| syntax_predicate_id | skos:relatedMatch |
| object_id | MIXS:0000016 |
| object_value_syntax - expected_value - unit | {text}|{termLabel} {[termID]} - text or OBI |
| syntax_comment | DwC expects the name of, reference to, or description (which could also include a URI, IRI, etc.), while MIxS expects terms from an ontology where appropriate, for which the input would not only be a word but a termLabel[termID] combination |

**Comment by pbuttigieg** [comment]
The semantic match may actually be DwC narrowMatch MIxS, as the MIxS expectation is more restrictive.

**Comment by pbuttigieg** [comment]
The syntactic match is a bit funny here and in a few other cases: they're "related" in a broad sense, but what we're actually saying is that they're not really related. Not sure what the right way to handle that is.
