### ISSUE TITLE
DwC Mapping - MIXS:0000001 samp_size

### ISSUE THREAD

**Issue by tucotuco** [tdwg/gbwg#22]
| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/sampleSizeValue |
| subject_definition | A numeric value for a measurement of the size (time duration, length, area, or volume) of a sample in a sampling event. |
| subject_usage_notes | A sampleSizeValue must have a corresponding sampleSizeUnit. |
| subject_examples | `5` for sampleSizeValue with `metre` for sampleSizeUnit. |
| predicate_id | skos:broadMatch |
| object_id | MIXS:0000001 |
| object_label | samp_size |
| object definition | Amount or size of sample (volume, mass or area) that was collected |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment | dwc:sampleSizeValue requires the units of the measure to be given in dwc:sampleSizeUnit. |

and

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/sampleSizeUnit |
| subject_definition | The unit of measurement of the size (time duration, length, area, or volume) of a sample in a sampling event. |
| subject_usage_notes | A sampleSizeUnit must have a corresponding sampleSizeValue, e.g., `5` for sampleSizeValue with `metre` for sampleSizeUnit. |
| subject_examples | `minute`, `hour`, `day`, `metre`, `square metre`, `cubic metre` |
| predicate_id | skos:broadMatch |
| object_id | MIXS:0000001 |
| object_label | samp_size |
| object definition | Amount or size of sample (volume, mass or area) that was collected |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment | dwc:sampleSizeUnit  must accompany the measure given in dwc:sampleSizeValue. |

**Comment by 79-6d** [comment]
Related MIxS v6 issue: https://github.com/GenomicsStandardsConsortium/mixs/issues/72

**Comment by raissameyer** [comment]
Suggested syntax predicate for the mapping above https://github.com/tdwg/gbwg/issues/22#issue-805176461

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/sampleSizeValue |
| subject_value_syntax - expected_value - unit | {float} - measurement value |
| syntax_predicate_id | skos:narrowMatch |
| object_id | MIXS:0000001 |
| object_value_syntax - expected_value - unit | {float}{unit} - measurement value - millliter, gram, milligram, liter |
| syntax_comment | MIxS expects {float} {unit}, while DwC only expects {float} |

and 

| Field | Value |
| ----- | ----- |
| subject_id | http://rs.tdwg.org/dwc/terms/sampleSizeUnit |
| subject_value_syntax - expected_value - unit | {unit} - measurement unit |
| syntax_predicate_id | skos:narrowMatch |
| object_id | MIXS:0000001 |
| object_value_syntax - expected_value - unit | {float}{unit} - measurement value - millliter, gram, milligram, liter |
| syntax_comment | MIxS expects {float} {unit}, while DwC only expects {unit} |
