### ISSUE TITLE
DwC Mapping - MIXS:0000091 url

### ISSUE THREAD

**Issue by tucotuco** [tdwg/gbwg#23]
| Field | Value |
| ----- | ----- |
| subject_id | http://purl.org/dc/terms/references |
| subject_definition | A related resource that is referenced, cited, or otherwise pointed to by the described resource. |
| subject_usage_notes |  |
| subject_examples | `http://arctos.database.museum/guid/MVZ:Mamm:165861`, `http://www.catalogueoflife.org/annual-checklist/show_species_details.php?record_id=6197868` |
| predicate_id | skos:closeMatch |
| object_id | MIXS:0000091 |
| object_label | url |
| object definition |  |
| object source | https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx |
| comment | This mapping is a guess, given that the MIxS url term does not have a definition provided. |

**Comment by 79-6d** [comment]
Related MIxS v6 issue: https://github.com/GenomicsStandardsConsortium/mixs/issues/67

**Comment by raissameyer** [comment]
The subject is currently from the Dublin Core namespace. We may want to consider adding [dwc:associatedReferences](https://dwc.tdwg.org/list/#dwc_associatedReferences) instead (or [dwc:associatedMedia](https://dwc.tdwg.org/list/#dwc_associatedMedia), or even [dwc:associatedSequences](http://rs.tdwg.org/dwc/terms/associatedSequences), as the MIxS term is so broad in scope)

**Comment by pbuttigieg** [comment]
>Related MIxS v6 issue: GenomicsStandardsConsortium/mixs#67

Thanks @79-6d - this link can go into the SSSOM comment on this mapping
