### ISSUE TITLE
Capture value syntax recommendations in DwC-MIxS mapping

### ISSUE THREAD

**Issue by raissameyer** [tdwg/gbwg#28]
While most MIxS terms specify a constrained value syntax, many of the mapped DwC terms are "verbatim". 

We will have to consider this in addition to the definitions when choosing mapping predicates. We will add a column to the mapping spreadsheet to capture this.

Moreover, the mapping predicates may change depending on the direction of the mapping (e.g. see issue #15). 

**Example**
For MIxS elevation the value syntax is constrained to be {float}{unit}, however for verbatimElevation it could be anything, e.g. 1 m 5 cm, so {float}{unit}{float}{unit}, etc.
Here, for taking MIxS into DwC skos:exactMatch is fine, however, if the mapping goes from DwC to MIxS there is no guarantee that the value syntax pattern will be matched. We are currently mapping in the direction of DwC to MIxS, so it would be a skos:broadMatch (because the subject is DwC and the object is MIxS, the DwC would always be broader because there could be a wider range of syntax coming from verbatim)

**Comment by tucotuco** [comment]
Do you think it is best to add reverse mapping predicates to the existing
issues?

**Comment by 79-6d** [comment]
What do you think about MIxS terms that might not be mapped to a Darwin Core term but could be the values of Darwin Core fields? 

Take the elevation term for example, it can be fitted into [Darwin Core Measurement or Fact](https://dwc.tdwg.org/terms/#measurementorfact) extension like this:

```
[measurementType](http://rs.tdwg.org/dwc/terms/measurementType): elevation
[measurementValue](http://rs.tdwg.org/dwc/terms/measurementValue): 1.05
[measurementUnit](http://rs.tdwg.org/dwc/terms/measurementUnit): meter
```

I believe many MIxS terms could be fitted this way (especially the ones from various environmental packages) into Darwin Core even though they could not be mapped semantically. 

Darwin Core terms like these including [sampleSizeValue](http://rs.tdwg.org/dwc/terms/sampleSizeValue), [sampleSizeUnit](http://rs.tdwg.org/dwc/terms/sampleSizeUnit) will have broad usage that might not be mapped with any MIxS fields, I guess?
