### ISSUE TITLE
Task Group (proposed) for MIxS-DwC alignment

### ISSUE THREAD

**Issue by pbuttigieg** [tdwg/gbwg#4]
Dear GBWG team @ramonawalls 

@raissameyer and I have created a task group proposal to consolidate this multi-year thread [here](https://docs.google.com/document/d/1KvcOmxwLJWAO889wpmcLUpxnI3lhx1vWoXnH9nuEsC8/edit#). 

This issue is to notify the GBWG community and respond to questions. It's also a chance to consolidate issues like #3

**Comment by timrobertson100** [comment]
The [charter](https://www.tdwg.org/community/gbwg/MIxS/) has been approved, and the task group formerly exists. 
A folder is created in this repository to capture work, and the mailing list is created for discussion.

I suggest closing this issue @pbuttigieg and opening specific issues for the task group to address.

Please let me know (trobertson@gbif.org) if you need any changes made.

**Comment by pbuttigieg** [comment]
Many thanks @timrobertson100 - I agree and will close this issue, replacing it with a Project to manage issues
