### ISSUE TITLE
Projects for issue management 

### ISSUE THREAD

**Issue by pbuttigieg** [tdwg/gbwg#5]
@timrobertson100

Following on from #4 - I don't seem to be able to create GH Projects. Is this a permissions issue (I don't seem to have admin rights here, which would be needed for me and @raissameyer) or should we use Labels to mark TG-specific issues instead?

**Comment by timrobertson100** [comment]
I've enabled projects for this repository.

**Comment by timrobertson100** [comment]
@pbuttigieg you need to accept the email invitation to be an admin of this repository I see.
You might be able to accept it here, https://github.com/tdwg/gbwg/invitations or check your email (was a while ago)
