### ISSUE TITLE
SSSOM - split semantic and syntactic predicates

### ISSUE THREAD

**Issue by pbuttigieg** [tdwg/gbwg#54]
xref https://github.com/mapping-commons/sssom-py/issues/22

The semantic predicate would focus only on the meaning of each field in the subject/object pair, while the syntactic would note if users can expect a syntax alignment or not. Very useful when writing import functions.

Syntax mismatches can be the result of using different units, value formats, including units in values, etc. - not sure if we want other predicates for each of those cases (may be too much)

In our report, we should recommend closer syntactic alignment or at the very least stability / standard syntax so stable converters can be written.

**Comment by raissameyer** [comment]
I've now added suggestions for syntax_predicates to all our mappings (see our SSSOM spreadsheet and [corresponding issues](https://github.com/tdwg/gbwg/issues?q=is%3Aopen+is%3Aissue+label%3A%22DwC+Mapping%22).

For any measurement values, I've used
- `skos:narrowMatch` if the mapping was from DwC {float} to MIxS {float}{unit} and both expected the same float (`skos:broadMatch` for the reverse mapping?)
- `skos:relatedMatch` if the mapping was from DwC expecting "verbatim" to MIxS expecting {float}{unit}
- `skos:relatedMatch` if the mapping was from DwC expecting a negative value to MIxS expecting a positive value

**Comment by tucotuco** [comment]
I don't know if this was covered anywhere else, but would this separation
not also suggest that the actual definitions be updated to separate the
semantic and syntactic parts? As they are, combined, they often suggest
distinct concepts where the "idea" is the same, but the way it is captured
is incompatible.
