### ISSUE TITLE
quotes around ORCIDs and CURIES

### ISSUE THREAD

**Issue by wdduncan** [tdwg/gbwg#68]
I don't think we need the quotes around the ORCIDs and CURIEs in the SSSOM headers. E.g.,:
```
#creator_id:
#  -"https://orcid.org/0000-0003-1336-5554"
#  -"https://orcid.org/0000-0001-9625-1899"
#  -"https://orcid.org/0000-0002-6601-2165"
#  -"https://orcid.org/0000-0003-1144-0290"
#  -"https://orcid.org/0000-0002-8083-6048"
```

```
#curie_map:
#  dwc: "http://rs.tdwg.org/dwc/terms/"
#  dwcversion: "http://rs.tdwg.org/dwc/terms/version/"
#  dcterms: "http://purl.org/dc/terms/"
```

**Comment by raissameyer** [comment]
The quotes were included following the [SSSOM examples](https://github.com/mapping-commons/SSSOM/blob/master/SSSOM.md#tsv). 

@wdduncan, @cmungall - are they are needed for SSSOM compliance? Otherwise I'd be happy to remove them.

**Comment by wdduncan** [comment]
For the DWC-MIXS mapping we are removing quotes from the CURIES.   
cf. SSOM issue [51](https://github.com/mapping-commons/SSSOM/issues/51)
